package primeirob.aulas.auladois;

public class Vector {

    public static void main(String[] args) {

        int[] declaracao;
        int[] declaracaoVetor;

        char[] string = new char[20];
        char valorChar = 68;
        char[] meuNome = new char[] { 'S', 'A', 'N', valorChar, 'R', 'O' };
        int[] valores = new int[] {20, 47, 12};

        System.out.println(meuNome);
        System.out.println(valores[1]);
    }
}